# Copyright (c) 2024-2025 rl_sar
# SPDX-License-Identifier: Apache-2.0

d1:
  dt: 0.005
  decimation: 4
  fixed_kp: [80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0]
  num_of_dofs: 12
  wheel_indices: []
  torque_limits: [33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5]
  default_dof_pos: [ 0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50]
  joint_names: ["FR_ABAD_JOINT", "FR_HIP_JOINT", "FR_KNEE_JOINT",
                "FL_ABAD_JOINT", "FL_HIP_JOINT", "FL_KNEE_JOINT",
                "RR_ABAD_JOINT", "RR_HIP_JOINT", "RR_KNEE_JOINT",
                "RL_ABAD_JOINT", "RL_HIP_JOINT", "RL_KNEE_JOINT"]
  joint_controller_names: ["FR_ABAD_controller", "FR_HIP_controller", "FR_KNEE_controller",
                           "FL_ABAD_controller", "FL_HIP_controller", "FL_KNEE_controller",
                           "RR_ABAD_controller", "RR_HIP_controller", "RR_KNEE_controller",
                           "RL_ABAD_controller", "RL_HIP_controller", "RL_KNEE_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
